sandboxnu/faculty-activity-tracker

- prisma/migrations/20230205215107_init/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- yarn.lock
> changed semesters to list

- prisma/migrations/20230209221759_init/migration.sql
- prisma/migrations/20230209223002_init/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
Modified schema and seed data to be integers instead of datetime type
> Updating datetime to int

- prisma/seed.ts
- src/pages/_app.tsx
- src/pages/submissions/[category].tsx
- src/shared/components/Header.tsx
- src/shared/components/SideNavbar.tsx
- src/styles/utilities.css
Beginnings of the new navbar. Navbar is on the left-hand side, and includes sublinks within "Submissions" for teaching/research/service.
> New Navbar

- package.json
- prisma/schema.prisma
- src/models/activity.model.ts
- src/pages/api/activities/[id].ts
- src/pages/api/activities/index.ts
- src/services/activity.ts
- yarn.lock
Cleaned up post/get route, added update route, and refactored these to match the current schema. Added a default value for the dateModified attribute in the schema, which will default to the current Unix timestamp if no value is specified when an activity is created. I also added prettier 😎
> resolves refactoring activity routes ticket

- next.config.js
- src/pages/dashboard.tsx
- src/pages/index.tsx
* Setup a redirect to send `/` to `/dashboard`
* Made dashboard page display the welcome message
> Redirected index to Dashboard page

- prisma/schema.prisma
- prisma/seed.ts
- src/client/accessCodes.client.ts
- src/client/users.client.ts
- src/components/AccountSetup/ProfessorInfoForm.tsx
- src/components/AccountSetup/RoleSetup.tsx
- src/components/AccountSetup/UserInfoForm.tsx
- src/components/ActivityForm/CategorySelector.tsx
- src/components/ActivityForm/FormInput.tsx
- src/components/Profile/PercentageInfo.tsx
- src/components/Profile/ProfileInfo.tsx
- src/middleware.ts
- src/pages/account-setup.tsx
- src/pages/api/access-codes/index.ts
- src/pages/api/access-codes/obtain.ts
- src/pages/profile.tsx
- src/services/accessCode.ts
- src/shared/components/DropdownInput.tsx
- src/shared/components/InputContainer.tsx
- src/shared/components/TextAreaInput.tsx
- src/shared/components/Unauthorized.tsx
Pages for user-onboarding flow. The process is: 
1. enters access code to obtain role (faculty/mc member)
2. enters user info (name & preferred name) - name is pre-loaded from authorized google account
3. enters professor info (position, percentages, etc) - percentages are pre-filled when user selects a position
Onboarding Flow:
https://user-images.githubusercontent.com/57200118/232906371-fa268114-42ed-40b6-a01c-f034e14ff5b8.mov
Changes:
- added `/account-setup` page for onboarding flow
- added `RoleAccessCode` table to database, and added mock values to seed file
- access codes are currently hard-coded in database, but should be added to admin page in the future
- added api routes `/api/access-code` for access codes:
- POST `/api/access-code/obtain`: submit an access code and receive …
> User Onboarding

- tailwind.config.js
Ticket Link: [#51](https://github.com/sandboxnu/faculty-activity-tracker/issues/51)
- Standardized typography in the `tailwind.config.js` file as per the Figma
- Confirm whether the styles are being applied as intended
> Standardize typography in Tailwind

- src/client/accessCodes.client.ts
- src/client/activities.client.ts
- src/client/narratives.client.ts
- src/client/professorInfo.client.ts
- src/client/users.client.ts
Closes #59
Removed all instances of `localhost`
> Paramaterize the apiRoot constants in the src/client/*.ts files

- src/pages/_app.tsx
- src/pages/account-setup.tsx
- src/pages/admin.tsx
- src/pages/dashboard.tsx
- src/pages/index.tsx
- src/pages/invalid-email.tsx
- src/pages/profile.tsx
- src/pages/submissions/[category].tsx
- src/pages/submissions/edit.tsx
- src/pages/submissions/index.tsx
- src/pages/submissions/new.tsx
> Fix `_app.tsx` to prevent using `AppLayout` in every component

- src/pages/api/auth/[...nextauth].ts
> fix(auth): fixed mock user emails to use husky.neu.edu

- package.json
- src/shared/components/AppLayout.tsx
Closes #82 
* Added a progress bar at the top of the app to show loading
* How it looks and if its consistent with our look and feel
* Play around with it and see if it messes up at some places
> feat(header): Added a loading bar to show loading state when navigating to pages

- .github/workflows/main.yml
- src/components/ProfessorScoring/StaticScoreBubble.tsx
Closes #93 
- Updated workflow to prevent running it on individual branches since it is redundant given that it already runs on open pull requests
> Change GitHub Action workflow to only run on Pull Requests and Push to Main

- .github/workflows/main.yml
- src/pages/auth/signin.tsx
Closes #96
- Add `npx prisma generate` to Typescript Compiler job
> Fix broken Prisma types in CI job

- src/client/accessCodes.client.ts
- src/pages/admin.tsx
- src/pages/api/access-codes/index.ts
- src/pages/api/professor-scores/index.ts
- src/services/accessCode.ts
Closes #98 
- Add a "minimalistic" form for getting and setting the access codes
> [Admin page]: Add fields to add/edit access codes for faculty and MC roles

- tailwind.config.js
Closes #(Ticket Number)
* Added new gray color (gray 150 -> `#EBEBEB`)
> chore(tailwind): add new gray color

- README.md
> Docs: Updated logo url in readme

- src/components/AccountSetup/ProfessorInfoForm.tsx
- src/shared/components/DropdownInput.tsx
small onboarding cleanup that's included in the merit-onboarding branch that we want to include for the demo:
- add tooltip message for activity distribution and teaching release explanation
- ensuresthat absolute dropdowns are above tooltip icons
> Onboarding Cleanup

- src/components/ProfessorScoring/NarrativeCard.tsx
Now the same display for narratives whether shortened (closed) or full (expanded).
Check that I've covered every other narrative (and activity) new lines related issue
> Update narrative cards on merit view

- src/components/ProfessorSearch/CommentBubble.tsx
- src/components/ProfessorSearch/ProfessorCard.tsx
- src/components/ProfessorSearch/ProfessorCardGroup.tsx
- src/pages/merit/professors/index.tsx
- src/services/professorInfo.ts
- src/services/professorScore.ts
- src/shared/components/InfoSidebar.tsx
- src/shared/utils/professorScore.util.ts
Closes #48 
Completed the professor page minus filter/search (Ignore the sidebar in the screenshot, that was from an earlier version)
the /merit/professors/index.tsx page
> Professor Search Page #48

- package-lock.json
- package.json
- prisma/faker/models.ts
- prisma/faker/seed.ts
- src/pages/merit/graphs.tsx
- Use faker.js to generate large amounts of seed data
- Remove mock data from graphs page and online use prod data
> Faker Seed Data

- src/components/ProfessorScoring/ActivityApprovalCard.tsx
- src/shared/utils/misc.util.ts
Closes #130 
- Added code to shorten the title using ellipsis and prevent text wrapping
- Set `overflow` property to `hidden` (very unlikely that a user's screen is small enough to cause an overflow)
> MC: Individual Professor Page
